#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# This wizard writes two files, both gitignored:
#   front-end/.env.oci          — OCI/registry values (region, namespace)
#   front-end/.env.oci.secrets  — runtime secrets for the Container Instance
# Keep them in separate files so the registry/region values (harmless to
# leave lying around) don't sit in the same place as real DB credentials.
ENV_FILE="$(dirname "$0")/../.env.oci"
SECRETS_FILE="$(dirname "$0")/../.env.oci.secrets"
IMAGE_NAME="sus-mais-inteligente-frontend"
WALLET_PATH="${WALLET_PATH:-$HOME/Downloads/Wallet_INTELIGENTESUS.zip}"

banner "Deploy SUS Mais Inteligente to OCI Container Instances"

# ── Stage 1: OCI CLI ────────────────────────────────────────────────────
stage "OCI CLI"
if command -v oci >/dev/null 2>&1 && oci iam region list >/dev/null 2>&1; then
  say "OCI CLI is already installed and configured — skipping."
else
  if ! command -v oci >/dev/null 2>&1; then
    say "OCI CLI isn't installed. Installing via Homebrew (this repo already assumes"
    say "a Mac dev environment)."
    if confirm "Install oci-cli with 'brew install oci-cli' now?"; then
      brew install oci-cli
    else
      warn "Skipping install — re-run this wizard once the OCI CLI is on your PATH."
      SKIPPED+=("Install the OCI CLI (brew install oci-cli)")
    fi
  fi
  if command -v oci >/dev/null 2>&1; then
    say "Now the interactive OCI CLI setup — it creates an API signing key and"
    say "config file for you, using your OCI username, tenancy OCID, and region."
    step "Have your OCI username handy. Tenancy OCID and region are shown in the"
    step "Console under Profile (top-right) → Tenancy: <name>."
    open_url "https://cloud.oracle.com"
    if confirm "Run 'oci setup config' now?"; then
      oci setup config
    else
      SKIPPED+=("Run 'oci setup config'")
    fi
  fi
fi
pause

# ── Stage 2: Tenancy namespace & region key (for the OCIR image URL) ────
stage "Registry address"
say "Oracle Container Registry (OCIR) image URLs look like:"
say "  <region-key>.ocir.io/<tenancy-namespace>/<repo>:<tag>"
say ""
say "Fetching your tenancy's Object Storage namespace (same value OCIR uses)..."
if command -v oci >/dev/null 2>&1 && TENANCY_NAMESPACE_AUTO=$(oci os ns get --query 'data' --raw-output 2>/dev/null); then
  say "Found it: ${TENANCY_NAMESPACE_AUTO}"
else
  TENANCY_NAMESPACE_AUTO=""
  warn "Couldn't fetch it automatically (OCI CLI not configured yet?) — you can find it"
  warn "in Console under Governance & Administration → Tenancy Details → Object Storage Namespace."
fi
ask TENANCY_NAMESPACE "Tenancy namespace:" || true
[[ -z "${TENANCY_NAMESPACE:-}" && -n "$TENANCY_NAMESPACE_AUTO" ]] && TENANCY_NAMESPACE="$TENANCY_NAMESPACE_AUTO"
write_env TENANCY_NAMESPACE "$TENANCY_NAMESPACE"

say ""
say "Region key: the ADB wallet connects to sa-saopaulo-1, whose OCI region key is"
say "usually 'gru' — but confirm on this docs page (search 'São Paulo'):"
open_url "https://docs.oracle.com/en-us/iaas/Content/General/Concepts/regions.htm"
ask OCI_REGION_KEY "Region key (e.g. gru):"
write_env OCI_REGION_KEY "$OCI_REGION_KEY"

OCIR_HOST="${OCI_REGION_KEY}.ocir.io"
OCIR_REPO="${OCIR_HOST}/${TENANCY_NAMESPACE}/${IMAGE_NAME}"
write_env OCIR_REPO "$OCIR_REPO"
say ""
say "Registry path resolved to: ${OCIR_REPO}"
pause

# ── Stage 3: Auth token + docker login ───────────────────────────────────
stage "Docker login to OCIR"
warn "Use an Auth Token here, NOT your regular OCI password — same gotcha as the"
warn "README's other Oracle auth pitfalls (wrong credential = silent auth failure)."
step "Profile (top-right) → My profile → Auth tokens → Generate token."
step "Copy the token now — Oracle only shows it once."
open_url "https://cloud.oracle.com/identity/domains/my-profile/auth-tokens"
ask OCIR_USERNAME "Your OCI username (the one you log in with):"
ask_secret OCIR_AUTH_TOKEN "Paste the auth token:"
say "Logging in..."
if echo "$OCIR_AUTH_TOKEN" | docker login "$OCIR_HOST" -u "${TENANCY_NAMESPACE}/${OCIR_USERNAME}" --password-stdin; then
  say "Docker is now authenticated to ${OCIR_HOST}."
else
  warn "docker login failed. If your account is federated (IDCS/SSO), the username"
  warn "may need to be '${TENANCY_NAMESPACE}/oracleidentitycloudservice/${OCIR_USERNAME}' instead — retry manually if so."
  SKIPPED+=("docker login to $OCIR_HOST")
fi
pause

# ── Stage 4: Build, tag, push ─────────────────────────────────────────────
stage "Build & push the image"
say "Building for linux/amd64 — Ampere (ARM) shapes aren't available in this"
say "tenancy's region, so the Container Instance runs on an x86 shape instead."
note "Cross-building amd64 on Apple Silicon uses QEMU emulation via buildx, so this"
note "step is noticeably slower than a native build — that's expected, not stuck."
FRONTEND_DIR="$(dirname "$0")/.."
IMAGE_TAG="$(date +%Y%m%d-%H%M%S)"
say "Tag: ${IMAGE_TAG} (also tagging :latest)"
( cd "$FRONTEND_DIR" && docker buildx build --platform linux/amd64 \
    -t "${OCIR_REPO}:${IMAGE_TAG}" -t "${OCIR_REPO}:latest" \
    --push . )
write_env LAST_PUSHED_TAG "$IMAGE_TAG"
say "Pushed ${OCIR_REPO}:${IMAGE_TAG} and ${OCIR_REPO}:latest."
note "If this failed with a 404/NotAuthorized on first push, the repository doesn't"
note "exist yet and your account lacks auto-create policy — create it manually first:"
note "Developer Services → Containers → Container Registry → Create Repository"
note "(name it '${IMAGE_NAME}', private)."
pause

# ── Stage 5: Runtime secrets for the container ────────────────────────────
stage "Oracle runtime secrets"
say "These five env vars are what front-end/ui_common.py reads at startup —"
say "written to ${SECRETS_FILE}, kept separate from ${ENV_FILE} and gitignored."
say ""
if [[ -f "$WALLET_PATH" ]]; then
  say "Found the wallet at ${WALLET_PATH} — encoding it."
  ORACLE_WALLET_ZIP_B64="$(base64 < "$WALLET_PATH" | tr -d '\n')"
  ENV_FILE="$SECRETS_FILE" write_env ORACLE_WALLET_ZIP_B64 "$ORACLE_WALLET_ZIP_B64"
else
  warn "Wallet zip not found at ${WALLET_PATH}."
  ask WALLET_PATH_INPUT "Full path to the wallet .zip:"
  if [[ -f "$WALLET_PATH_INPUT" ]]; then
    ORACLE_WALLET_ZIP_B64="$(base64 < "$WALLET_PATH_INPUT" | tr -d '\n')"
    ENV_FILE="$SECRETS_FILE" write_env ORACLE_WALLET_ZIP_B64 "$ORACLE_WALLET_ZIP_B64"
  else
    warn "Still not found — skipping. Add ORACLE_WALLET_ZIP_B64 to ${SECRETS_FILE} by hand:"
    warn "  base64 < /path/to/Wallet_INTELIGENTESUS.zip | tr -d '\\n'"
    SKIPPED+=("ORACLE_WALLET_ZIP_B64 in $SECRETS_FILE")
  fi
fi
ENV_FILE="$SECRETS_FILE" ask ORACLE_USER "Oracle DB username (e.g. ADMIN or USR_FRONTEND):"
ENV_FILE="$SECRETS_FILE" write_env ORACLE_USER "$ORACLE_USER"
ENV_FILE="$SECRETS_FILE" ask_secret ORACLE_PASSWORD "Oracle DB password:"
ENV_FILE="$SECRETS_FILE" write_env ORACLE_PASSWORD "$ORACLE_PASSWORD"
ENV_FILE="$SECRETS_FILE" ask_secret ORACLE_WALLET_PASSWORD "Wallet password (set when the wallet .zip was downloaded — different from the DB password):"
ENV_FILE="$SECRETS_FILE" write_env ORACLE_WALLET_PASSWORD "$ORACLE_WALLET_PASSWORD"
ENV_FILE="$SECRETS_FILE" ask ORACLE_DSN "TNS alias [inteligentesus_high]:"
ORACLE_DSN="${ORACLE_DSN:-inteligentesus_high}"
ENV_FILE="$SECRETS_FILE" write_env ORACLE_DSN "$ORACLE_DSN"
pause

# ── Stage 6: Create the Container Instance ────────────────────────────────
stage "Create the Container Instance"
say "This part is Console-driven — Container Instance creation has enough moving"
say "parts (shape, VNIC, per-container env vars) that clicking through the actual"
say "current UI is more reliable than a guessed CLI command."
open_url "https://cloud.oracle.com/compute/container-instances/create"
say "Fill in:"
step "Name: sus-mais-inteligente-frontend"
step "Compartment: wherever your existing Compute Instances live (reuse it, don't"
step "  create a new one — keeps this on the same network as the rest of the stack)."
step "Availability domain: same as your existing Compute Instances."
step "Shape: an x86 flex shape, e.g. CI.Standard.E4.Flex (Ampere/ARM shapes aren't"
step "  available in this region) — 1 OCPU / 6 GB is plenty for a Streamlit app this size."
step "Networking: pick the SAME VCN/subnet as your existing Compute Instances (so it"
step "  can reach the internet the same way they do), and enable 'Assign a public IP'"
step "  — this app is public-by-design for the MVP (no auth gate, see ADR-0001)."
step "Container image: ${OCIR_REPO}:latest"
note "  (Console may ask you to add OCIR as an image source / re-auth with the same"
note "  auth token from Stage 3 if this is the first container instance in this compartment.)"
step "Container → Environment variables: add all five keys from ${SECRETS_FILE}"
step "  (open it in an editor now — never paste secrets into chat/logs):"
say "  ORACLE_USER, ORACLE_PASSWORD, ORACLE_WALLET_PASSWORD, ORACLE_DSN, ORACLE_WALLET_ZIP_B64"
step "Create."
confirm "Container instance created and shown as PROVISIONING/ACTIVE in Console?" || \
  SKIPPED+=("Create the Container Instance in Console")
pause

# ── Stage 7: Verify it's live ──────────────────────────────────────────────
stage "Verify it's running"
say "Once the instance shows ACTIVE, its public IP is on the instance's detail page"
say "(Networking section)."
ask CONTAINER_INSTANCE_URL "Public IP or URL (paste it once you have it, or leave blank for now):"
if [[ -n "${CONTAINER_INSTANCE_URL:-}" ]]; then
  write_env APP_URL "http://${CONTAINER_INSTANCE_URL}:8501"
  say "App should be reachable at: http://${CONTAINER_INSTANCE_URL}:8501"
  note "(port 8501 is Streamlit's default — the Dockerfile EXPOSEs it; if you fronted"
  note "it with a load balancer on 80/443 instead, use that URL)."
else
  SKIPPED+=("Confirm the public URL once the instance is ACTIVE")
fi
pause

# ── Stage 8: How to update later ───────────────────────────────────────────
stage "Updating later"
say "To ship a new build after code changes, you don't need to redo Stages 1-3."
say "Just re-run:"
say ""
say "  ${BOLD}front-end/scripts/deploy_to_oci.sh${RESET}"
say ""
say "It's idempotent — Stages 1-3 will detect existing config and let you Enter-through"
say "them. Stage 4 always builds+pushes a fresh timestamped tag plus :latest. Then:"
step "In Console, open the container instance → Containers tab → your container →"
step "  Edit (or Restart, if it's already tracking :latest) → confirm the image"
step "  reference is still ${OCIR_REPO}:latest → Save/Restart."
note "OCI Container Instances don't auto-pull a new :latest on their own — you must"
note "explicitly trigger a restart/update in Console (or via 'oci container-instances"
note "container update --help' if you'd rather script it — check that command's"
note "current flags yourself; this wizard doesn't guess at OCI CLI syntax it hasn't verified)."
pause

finish
